name: Reusable Release Drafter

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Log github.ref_name
        run: echo "github.ref_name is ${{ github.ref_name }}"
      - uses: release-drafter/release-drafter@v6
        with:
          commitish: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}