name: Reusable Release Drafter

on:
  workflow_call:
    
permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          contents: write
          pull-requests: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}